#ifndef ProjectConfuse_h
#define ProjectConfuse_h
//confuse string at Thu Apr 25 12:11:18 CST 2019
#define HttpTools yldGRmwenNhZOEto
#define httpConnect QvBAqSGQQzQFETrr
#define url smDXoLsOVlDAJYzr
#define type ftqJXWYyZQVkQnay
#define headers yLDUZZSUiuQrkoFI
#define uploadDic IlpRoDRnxCowMcTX
#define callback VlPzaPfSPLGkWAah
#define resultStatus LXVCstMqjpIscRAm
#define resultHeaders TgosoOYqlmpRehZi
#define resutlData SREpPGcvvqugdzga
#define resultError RpBVjkwDhBqWTpyg
#define request rMcOyPdfNgFJFPHN
#define session TIVjOrVpiGBXOlNN
#define task uHcRWqdTuktdQVvG
#define data ZqRXxFZxIJsSIHZJ
#define response nBzqApHVBUgrLHqN
#define error DyTeWUREiSkHZbmy
#define httpResponse bCywCAbazHkXhwrr
#define headerKey XtbgYuZIoNLIIlRH
#define headerValue wWOmPTCfOZoaeYyB
#define downloadJasonDataAsDictionary MaAxuIrUQCKRwMjp
#define resultDic xhfuDFimvdLfJeFy
#define errorString aUJdArBAVOaNKSUc
#define downloadJasonDataAsArray HJRcWdeWzgKeDrdU
#define resultArray TIoicFEAhtjVRvcU
#define downloadImage dBNhApsnuYoZvDNc
#define ClosureWrapper hFOmWJbKfMtduhAT
#define SplitViewController WHRJChVjnWviGthG
#define totalPageArray wtAJdSTEsgiHnSLM
#define totalCateArray wGwhlYbcxjjzLhyW
#define counter McTneeyFTTueAXio
#define naviVC ySYYAxiNDzKAmpEN
#define rootVC nkIjxfxWxVdudYMc
#define detailNavi ILoZAhweizmkPPLR
#define detailVC AbcGpBYfYOJVkGwG
#define userInfo nNJJmOLemMZPVumF
#define naviVCTemp UpFhMoEOOBCOmkLW
#define rootVCTemp RklvELnNyIuywQLD
#define detailNaviTemp fUmNACqzuwqJVblm
#define detailVCTemp ImcHChHaZlhpPpzN
#define vc knVGMRlbxlpWTuWp
#define lang tURyUxNkdrHiwmwQ
#define isRecommend qwmVtQenRGVXpSYQ
#define resetData HoptyxTdBQSPzicZ
#define totalPageArrayTemp iXdyWBTHhYfivEgP
#define totalCateArrayTemp brWwqzJfnaPMOrEt
#define newPageArray HeuSAhoBuDRLXggS
#define dataDic hVWZzenjHfGqSLHG
#define cateName eSYlVAuXMciikpxH
#define cateNameTemp tcBObaytbkPBUlPK
#define dataArray faBylsPlPrsEWoax
#define contentDic MmrthfCfDondThoC
#define pageContentObj rWSeCbmdxRHeAetH
#define titleName KBVnYLWkQogtcBDX
#define subName WhOihxfkeNFDjTRS
#define id oAkePjAANtECHmya
#define editTime dlqiGMEzruMJuDdh
#define imageUrl TDVltNkRTRmVkVKo
#define tagString kjRlvAfEGlSKXppQ
#define tagArray ULagRmllnqrfYkAz
#define attentionArray sFyaSWEQWptwKyps
#define indexTemp eeAuIhJzmWNXqXsL
#define attentionObj rWSNuaxLUddcrkTG
#define index GixeqaGNrEdxpLYU
#define resetRootViewData qyqUZkAxyCtDVmVE
#define resetDetailViewData IcfGBcZKOczTsXLl
#define checkLogin zMokppuQIzqKsSUq
#define loginVC wCBnfoxoqJoPuecA
#define registerVC qxMpFRzascjfkcbE
#define showRecommend BXEDeTIbWORMykAl
#define maintenanceUrl tBnTNdpqGGCUQopT
#define foodArray GnnsBQixihQBjDdT
#define overWebVC RJATlgdvOPdmOcrg
#define foodDic kQrbNBvuHUJulexT
#define titleNameTemp fizlDPRuTYPqOCJj
#define contentUrl TtaNvhmBtjrXUIog
#define contentUrlTemp ughNsolxldPUuMKU
#define accObj QHUIGFXzMBMfbELV
#define RootViewController GijcLKegFcZdZPlq
#define rootTV WqMEjrZMIUsSosSU
#define RootTableView GMEJjIHxiGFOhkFS
#define rtInstance cKtjQPGxlIuviSwT
#define rootViewDataArray rYWkAgfPXHosfUtM
#define cell cOXrMPwOWOjzpdQT
#define spVC IAeiSxwcUGQmrTya
#define iconImageView mCKgiBfhoEUODtgD
#define iconImageWidth CzaBymKEwWXehSdU
#define nameLabel qfQTULwppygdReaq
#define NavigationController vfRBDwCVRsTXXLXu
#define DetailNavigationController GsjkAXTODSQpHpoa
#define ViewController YZmNgxzNOsFJqNtv
#define viewControllerTV djCoAVpOQinDOskV
#define noneLabel QnfrlnGsPBuykSHi
#define searchController WnEWfGXNRCMpjAgE
#define homeName grSrOVPqVRJFWCNt
#define attentionName VrKgeNfPTQmCGwYG
#define postName PJVTCmHrofWivyhV
#define commentName NpOYMAehwyCNYdZg
#define userInfoName HhNsLXCYXZMUOauS
#define noneAttentionName CuTvDpjTpXNJrzIo
#define searchPlaceholderName xXvHaElamUNWhEva
#define searchBarBgColor PbdEAbYYCPhoLQox
#define searchBarTextColor gykYEeWvEaROREIn
#define searchBarButtonColor JBJBdvDSvAxKBOSF
#define selectCateName RZIeQbeuUruOJTuc
#define toolbarSelectIndex dFDZdlCJOEUNTYxD
#define featuresName RIHgdIROeeIpbxkk
#define toolbarHeight OtEgbxdrcZdRpCbr
#define toobarWidth ItChffgfrmXFFbey
#define toolItems xrXQAgrxOtUctjsd
#define homeBtn TiYHVlMBtNCMmWGj
#define attentionBtn MhSlTdArZJalPhrE
#define postBtn bmiSXEalWHuMfxvQ
#define commentBtn VvBCOiiZtWdCWECD
#define userInfoBtn joktnGytuRQvAQZY
#define showAttention IgIklwErgcLDEPPm
#define showPost bioWBeydnjBmoqdm
#define storyBoard EBglbTMPnssBARHg
#define nextVC JKQybpCbRDxpzFus
#define showComment BIkHTlUhhgLJIaph
#define discussVC jvKkYkQkCeICmHYh
#define discussObj zApVFXCMgZkwZGKo
#define repostVC yPHLLBFPBueTvAqK
#define showUserInfo jSPsxCMeSipxBZKj
#define updateCateSelect UwlcUtsbtPkkAloL
#define spVC bIMxeRvduGTmDmSB
#define rootVC ksXQUdAIvNZdzpKK
#define updateSearchResults gBzFoVPezZmSQmjY
#define isContains ydSbodaEnQhuQRFC
#define ViewControllerTableView NJRIcBwHrlenAGwP
#define vcInstance EsNOtzqmukLlJtQu
#define allDataList dPJJdzEupBBJGXCE
#define cateDataList FKfpKmnpHGlRriXe
#define showDataList lHISotVcgGiAUkiT
#define attIndexTemp BkpyMVnwuWIrzuJl
#define attIndex OslgppZSsegOzERN
#define cateIndex PwORMgMQYHrDtQfl
#define ViewControllerTableViewCell kmFXNjwWbJMyujcX
#define cellMainView yWeQzdaTuzsxGIrb
#define cateImageView vjZkEHMDKvTLwACG
#define cateTitleNameLabel iLfvOPaYlgliLDUw
#define cateSubTitleNameLabel IRplSDrcTGmIQiWJ
#define cateSelectBtn XplZMhFZnvleQDWO
#define cateAttentionBtn xqUlQobNqqdGMLDH
#define cateDetailBtn GmtlcVwFcMhdxMSq
#define mainColor iwvUclYgbCHHvGdU
#define subColor kWLKqFPEwTmgtIof
#define PostViewController huOztACXMRwwvRLf
#define cateArrowImage qXUdyhseWvyRsXWq
#define cateView dWvYQmClKrjlbnCe
#define cateLabel ORGjHObvaaXdnLkB
#define mainLabel JeMoDcrzcbBTDOtq
#define subLabel NGQYTYoirohQZSEe
#define urlLabel baxFhMQFaeMCpUzO
#define tagTitleLabel zBtnDRjutYotdvSY
#define imageLabel AKZrwcAQYtZvqbUA
#define spinner HGRmqfGMQVWQRdTy
#define mainTextField LUXssBUpXQcEFXAj
#define subTextField wpTVgJuEXKrpBVdO
#define urlTextField nKilhsNTgIZbwbCU
#define tagLabel tsuXOlCwZVzsOAns
#define tagAddBtn jQLCKwwAFBJBvWvV
#define postImageIndicator dUbkPYnEjspMbJSh
#define postImageView PyUxRRGsybcDXDaX
#define postImageViewHeight uEfwmSByqjdnoiWB
#define postImageBtn HYzIZuwkbRfLeHOF
#define sendIndicatorView VkwJYtuEjwbGLRuh
#define sendIndicator IHQRwUTpxZxRTvrQ
#define nextMenuId IbfVDBkJHVjrzaNn
#define imagePicker xjSFAADLkQwtfrtY
#define imageLink LEuNXfIRgZKMWwDn
#define controller aNBBYqEUsFUNkuqA
#define textField wIbArNOTGVCffame
#define okAction kPXZnUWbQKxxGshH
#define cancelAction ocvijYBoJNANeDEC
#define toolItems goOrtnTYojAovcoC
#define cancelBtn degGTgqYyfykwPvx
#define sendBtn YsbUgLkjijHRPzRX
#define newPageObj wnTCCYRdqipOBeis
#define df kphjalqbrEOnWUas
#define requestPhotoAuth qsdCLVBUmiNtfakF
#define photoAuthorizationStatus LpJRnaijueFAHONf
#define authorizationStatus XxbbVlLDrAMpmTgc
#define alertController drVcEOHsEeZSUdxh
#define pickedImage ZnWhiMPWOrhTWTUd
#define SimpleSpinner JbrjLpvABoaoBnxG
#define isEnable gIIeltczMisEAUsv
#define insideOfView gIMzikuhPiRfcljt
#define spinnerDefaultItemPosition HzoJcnFieYSciwKQ
#define spinnerLeftPadding sZNRFQKYpNlekMAw
#define spinnerRightPadding STsTZlHBCYqyUfFg
#define leftGapView RbtstcUXujfZvBUW
#define rightGapView iVquXiGfRQhUCXZE
#define spinnerTextFont UtfToTHMYvyZhqQT
#define spinnerTextColor fdvvJWVOFxaBhVHh
#define spinnerTextAlignment xEUhjfDuYEryFYYL
#define spinnerDropTextColor qqBRFoeWpXZBnBQC
#define spinnerDropBackgroundColor tmayrECOgEqSjSSJ
#define spinnerDropTextAlignment PYiKpFebTrBISkEX
#define spinnerItemPaddingTop sJBtxxjpLTwfavbI
#define spinnerItemPaddingBottom ivLZcXsfnJLdCznm
#define spinnerScrollView ziNjfJcUdbWYiiaG
#define spinnerCancelBtn odoECsoMYrmAxOJM
#define spinnerSourceView JvsfrrkpgxOwqgyg
#define spinnerLabel HiAyhHcVnfXSOPDh
#define spinnerTitleStringArray iKoXHWeqAvBCYTMa
#define spinnerCallback xIwFiTcIMyAWJfPk
#define createSpinner RqxFekSYZsLdpzPP
#define insideOfView IwGaAfkUrGizCQzM
#define topCons NYQcWLiMxXnkmZFr
#define bottomCons HRyxjgNAjrjRaZod
#define leadCons EnRxWbFKFsoOaHiu
#define trailCons XRHpypDjUdvulnjw
#define topConsLeftGap ohblmHMPfvqjcIYE
#define bottomConsLeftGap oILSezIlfUQhcKLF
#define leadConsLeftGap kggeLrUdvyBfVLST
#define widthConsLeftGap RIlrBpCfAWLQMtDv
#define topConsRightGap zFUMCLlaIdeNTlDX
#define bottomConsRightGap IqCwJdvkypdqBWCE
#define trailConsRightGap knKZlqjaWujnnPkG
#define widthConsRightGap vGYqvIHhifHKpjVM
#define heightConsLabel sOmOyMTkFBuxNTxI
#define widthConsLabel wCSKmzFLenhxLMBp
#define centerYConsLabel vfnrqbCZvRLuceko
#define leadConsLabel GjCMyJJKRiWSwPmv
#define trailConsLabel McZcEVZHdzMFgLUG
#define heightConsLabelView ogotTllIgqrNRJfq
#define spinnerBtn CJseODRdbBOIFwQF
#define topConsBtn odEyKVxkOhvlmevu
#define bottomConsBtn kKyswjLAPVwoIVhO
#define leadConsBtn qrqvMIkLuOKEZZWn
#define trailConsBtn BuhLCPTIJnqICHcK
#define removeSpinner uOzitjiuGDUtjIzd
#define spinnerScrollViewDisplay BiolVfEMZgSLrHcF
#define absFrame jZSKJdoaUEBdmdBq
#define outermostView PmlziuFdytSszbij
#define upSpace PlIiIkLWtCzYaISd
#define downSpace SmHnhcmsKXqsOFXL
#define useUp FUCVnVaZGNEBdrQe
#define maxWidth MTeUymBdmbtQUcRa
#define maxHeight hwOpCGmUxpebUhgF
#define cSize CMqYgtcgBZcFaUhB
#define cWidth wRRThHKTAvgdpymj
#define cHeight KZVNKroppimICUUS
#define displayItemCount rkuMhyJIldMSaDWi
#define topConsCancel ujfTzcJpnrHdQDGo
#define bottomConsCancel zXuykVNeRisgCGTE
#define leadConsCancel MhJIJlQrEyupHXGp
#define trailConsCancel pRvSwACNnZIEtINV
#define scrollContentView PZPSNTSQAXbmaGfW
#define topCons PcprjjiGYPMcWQBn
#define centerCons NxFSSFNPLLfBozJO
#define widthCons kuQBDinyzABssJqC
#define heightCons WPVAtQHxkUghlBCL
#define itemBtn saTZNMLIAGFyxKAg
#define btnHeightCons PAwyDMOdkhbAikhf
#define btnLeftCons hWtJwmgOubvHNZFN
#define btnRightCons pqpeWiLMsMYoRvUT
#define btnTopCons MuhBGllrldkrCKhm
#define currentItemBtn QaXxcGDWKSjmGgAA
#define itemBtn2 iBEAzuDqVpahWYRq
#define btnHeightCons2 gVlrcIGQgyZsQeda
#define btnLeftCons2 VzmAcYfzEwIznxhw
#define btnRightCons2 tFHmpGcxtVmlreZA
#define btnTopCons2 ULSqWjqFTziYMqMs
#define btnBottomCons mOyQBmNmqgCymdRu
#define spinnerScrollViewCancel tPpTLNcyceaAsEhh
#define spinnerScrollBtnClick PHamCfJwFxKAYkBp
#define setSelection JwyABAEdZdXAMLQM
#define getAbsoluteFame jxPmJYygcKzXZMDM
#define originX emecCdmswHnUfWJI
#define originY TQKFKwbZKXtrXmga
#define superView DYaaXbaabFNtyzUC
#define getOutermostView AGiPvHURPfaOBvmH
#define UserInfoViewController jbDnvQwNSkcOUpzX
#define userInfoTV LuXRLEiMzGrExONM
#define UserInfoTableView dvtxWwoHUVJRxqzH
#define vcInstance RlOhBpiDkwriPVUX
#define imagePicker DWAqCfEFEkQSsSxG
#define UserInfoTableViewCell EuMAUmuaZWmTxnBY
#define userImageView QQaKWWLbedPXGqRX
#define userImageIndicator hNhyFmVCiESmFuzH
#define userImageSelectBtn vttMaFOGgtbLFFxl
#define userNicknameTitleLabel bMPDQjVrnDTWFRcn
#define userNicknameLabel aUmQrpfKzjDsUVyD
#define userNicknameBtn zDWPIZLtHlYWpawd
#define userNicknameTextField fyHElgwUubxieJkL
#define userEmailTitleLabel zqDvPQAEFewaTXcJ
#define userEmailLabel YIHtPFQhTtYoeuPA
#define userEmailBtn pgWNoSESyDfiIGtR
#define userEmailTextField TURRslzjIbXVjXAM
#define SystemConfig OwuvARjZHLXmtEKq
#define appCateId TMWONeErxFKwMquo
#define appMainColor CDTfHWZfVFmXfyXF
#define appSubColor HiFsekVmLsDkfjHh
#define appSubTransColor daurmYepwrcABPsA
#define appMaskColor IOgYRtHWthKhWBab
#define appLightColor JgtciscfOmmHihoT
#define mTitleFont iTHhETUzPKtQfsdf
#define jpushAppKey DJQKMplQCHEJkzQx
#define jpushChannel aKxFKbHKkxaOtunz
#define leanCloudAppId GeNhrsRmrIfIekdu
#define leanCloudAppKey kTgICPMDUPkFTPLG
#define sendBirdAppKey RcxlXUjVlSJSSLSz
#define appSendBirdAccountChannelUrl jtHJopkNAGxUHJlj
#define appSendBirdNewPageChannelUrl KtnWQYyeDZEQsUCy
#define appSendBirdDiscussChannelUrl LhbhgWYyMqafyMTT
#define appSendBirdRepostChannelUrl YrDJYEVKGTFaTKyQ
#define appSendBirdLikeChannelUrl pIhoTGxlAOaNQDwC
#define appSendBirdAttentionChannelUrl YbtCjjZwITweBayt
#define RepostDiscussViewController VdpUpPxxjOnuWWTI
#define backgroundView dlmpzpvuHhxcCgXR
#define backgroundImageView sQPaPQSXBvsiWbnm
#define repostTV ErFRZGQeLWSyQwqo
#define sendView CkksHAqjVwHJwpDY
#define sendTextField ubmmZoitywLLexMu
#define sendBtn gbqZABvMawRLfDxX
#define sendBirdDiscussChannelUrl AorrLGPtZNHUnGyC
#define sendBirdRepostChannelUrl hSGUqHunJbtDxwSH
#define discussId UpMZOTeSDoYNqCap
#define discussObject ZODKXSNDqHjHUeuY
#define resetData lFIPgRflqzCpRRao
#define discussObjectTemp eBHiAZwdsKQbgLLo
#define repostObj nXgNvptMCxZTktcd
#define setParameter TPvGqFxVoTadNTmb
#define sendBirdDiscussChannelUrl bkipdWbpBaUsAxLl
#define sendBirdRepostChannelUrl eHPOPlrATtDvHSqB
#define discussId TZihfdrpGWdrXDIS
#define userInfo UjKMUqxLAGBttfvL
#define RepostDiscussTableViewCellM JBaODPChNNyOFTaY
#define cellBackgroundView NVLOdIMuhUlMaYvL
#define senderImageView uyfPtFVIefFeRlQg
#define senderNicknameLabel uwGRHbrBAdzNyqav
#define accordingImageView pWCBvQsXEWehZYjT
#define accordingTitleLabel mdquTGTxVBYtIVRy
#define accordingSubTitleLabel XRrOgFpRSPrXDEvr
#define subjectLabel tetSXPNJANlgWniL
#define contentLabel SJdCZMOZTcTsVWTn
#define RepostDiscussTableViewCellS IYQVetxoLXexjWar
#define cellBackgroundView VFqQhKzHnAxsgLQo
#define senderImageView mIvDbrVpLzOHXdst
#define senderNicknameLabel hxLVeBtGJRiruCIe
#define contentLabel pOrIDlKeajtdCBdh
#define dateLabel PSItKXPZgtVGZWaJ
#define QueryDiscussViewController vWmzzOnPPXvRdGHa
#define backgroundView FnAuUnhHeJRkDRBg
#define backgroundImageView HsFgTIWQYpcQMlmB
#define discussTV lrSQjlkFXsmYizze
#define sendBirdDiscussChannelUrl QKrIEcbNifavtNDY
#define sendBirdRepostChannelUrl UbpIcCkSTUNUTBhe
#define sendBirdLikeChannelUrl KXHeXeMngorxDLBQ
#define userInfo mQwVhxnUIjKlpitQ
#define discussArray WuDOmcXCzgnLQRVY
#define accordingClickCallback tCSIyCxFmiciMidw
#define repostClickCallback rBCwLCPooNEIaLLZ
#define sendBirdDiscussChannelUrl QetGJZybsWfvaAuP
#define sendBirdRepostChannelUrl IhaeRASoSlZDOiqw
#define sendBirdLikeChannelUrl gskhZrxZfgVPPhVb
#define accordingCallback qSJJpYJzigthBgxu
#define cellBackgroundView YGYauLvMFDdcvQaW
#define senderImageView XFSwQFMOOniZnqxV
#define senderNicknameLabel PzbTpHyOblWgPyMK
#define accordingImageView SBBILCrsvUpVMNIS
#define accordingTitleLabel pLfyvpCgjyfjyEmo
#define accordingSubTitleLabel oazGYnRAGxWWJxkC
#define accordingSelectBtn xyyMBwVarUfwmHIn
#define subjectLabel RysZhZGpkImDHJQb
#define contentLabel DHNLoJWFqbwHsJIW
#define dateLabel GBTyUMBYnlsRFfBr
#define repostBtn NunsmajRkvLEWGKT
#define likeBtn zAtfyaKROlQMeQhW
#define backgroundView tSHMgPKwvvbcinCW
#define backgroundImageView EqpuaJKfDBbxwVaw
#define sendDiscussView hJpHNIMRyeNImdJE
#define topBarView WRFqufbQUdzKzfNa
#define topBarTitleLabel pYHpzoLMUKKMwBlc
#define subjectTitleLabel tYBNXqkjBLtJifdY
#define contentTitleLabel iwlxKuebbGcRFLDa
#define subjectStrokeView LbwRbkNAJgYWkkUn
#define subjectTextField rPCsMHetXkwxWPng
#define contentStrokeView SmALiWCsoPPcmdEC
#define contentTextField oLcbOSYLDSLWpxmT
#define cancelBtn dlgIttoSeQAzyHxU
#define sendBtn AAQZLxNGpjYMqeDf
#define sendBirdDiscussChannelUrl NdXJwhzEFowCgILV
#define accordingObject deatDsZBREAqvYDo
#define sendClickCallback lBSZEGSOSWaIggjo
#define cancelClickCallback CsTDpLvCAHYHpctb
#define sendBirdDiscussChannelUrl keGDVqaTsmsNlGdm
#define accordingObj vEhYNCswXiQcwCsC
#define didSendCallback TDXaYRvoxoxSvunG
#define discussObj fOJDbEZxoqrnMuks
#define cancelCallback nyNElgMIEvDCNXsP
#define LoginViewController MNCnDqSxmAqGtSQS
#define backgroundView hMjAnqHCghDysxHw
#define backgroundImageView UHpVDRMRMUuHWAPW
#define loginView SSaTrGQvpBlUILpV
#define topBarView vlmPZtnXWJNbobvt
#define topBarTitleLabel vvETVkSFIObXBfiQ
#define accountTitleLabel MSRXpEVpyaSZkQKU
#define passwordTitleLabel sNSGJRqZlzJIqTUF
#define accountStrokeView PDQVMdCGWaGoJrKW
#define accountTextField YQQCCAkqvcojeuiO
#define passwordStrokeView sRrUVERnkJtSYcoc
#define passwordTextField EwbnsnYcTEdtpYkI
#define cancelBtn owRUdIYdjIRlJEHa
#define confirmBtn yPKFNNgwVYGqOQZK
#define sendBirdAccountChannelUrl gjRPOJpGzmmUOhZS
#define RegisterViewController NbusqyIppYWfIVxr
#define backgroundView gKpjwyblsSZomYiI
#define backgroundImageView VyyKlyxhFfsHDnDp
#define registerView SbNnJPavlSFXAgep
#define topBarView PtotcmXQJiuoWrsd
#define topBarTitleLabel ReYvTGOAgnhrGfMu
#define userImageView vxVGmxfQZIzbGuvN
#define userImageBtn pngCeAGTJQOfhmYD
#define nicknameTitleLabel WJHIRbfyyjNciwPP
#define emailTitleLabel jqwpLNJcxJyjSiWU
#define passwordTitleLabel KtbiZJLiKDeBmDlj
#define confirmTitleLabel qProgRpAOYVMhClj
#define nicknameStrokeView txlAHhCsTbsbTsDA
#define nicknameTextField QyIEYQGIOctjltUb
#define emailStrokeView toUwnIPjioFQlCcT
#define emailTextField uSMbBZvOStImusip
#define passwordStrokeView UonUKVQdkKQpFyIb
#define passwordTextField kkJNILgquRmPSgmZ
#define confirmStrokeView dFeoYVZFjrNeCcIa
#define confirmTextField mraAXYejPQwfBMgk
#define cancelBtn VqrFfBkzLdwtHEsn
#define submitBtn LHtoYSXMCwVYHDfG
#define submitClickCallback gSxvFBYHUNHawyKQ
#define cancelClickCallback fGMszJiooorMUcuy
#define imagePicker iFRakuMbMooRkdvZ
#define sendBirdLoginChannelUrl UfCvDZySbhwyudoK
#define userImageUrl hkIFomsKXTOtJyBJ
#define sendBirdLoginChannelUrl FrDOZaKPmkNjIxzT
#define sendBirdAccountChannelUrl jGAfYTfMZYrdnmHd
#define confirmClickCallback MbmfaLJDnsbaPsgX
#define cancelClickCallback gtsFKGnmrGmvmDmw
#define didRegistedCallback PunQyXGBRnAXaggY
#define OverWebViewController stxgarRrokXEvsQp
#define titleView kdNGqAcmqRJMHQoE
#define titleLabel vKhNLDMATKeQjCyi
#define toolsView WaJbmAhKLESlWABV
#define backBtn hQFqgIaWHFfFMAEI
#define forwardBtn CEoJrGMgUUouyFmO
#define refreshBtn kqePEhmjxkqDHQsJ
#define shareBtn QSYIPGeiVBXOMIJF
#define wkWebView GhoNVFjALPKZiWyu
#define exitName FUnAbyHxLBeqlNBE
#define backName bFLeuiYxzrOMUuSC
#define forwardName TsQndBejjNxJWXbw
#define refreshName bWNCgLQPWpeYLAyb
#define shareName xpDtccvqzCrBeveU
#define titleBarColor cCSoMtHJhplxGsRs
#define titleTextColor ZHzaLFPURjEhzZVl
#define titleTextSize bJVttWBdVbqvZSpY
#define toolsBarColor BjIeSDiakPLKlbDQ
#define toolsBtnColor TYmVhIytjTUMQYDe
#define toolsBtnTextEnableColor ctiKsFHytgQmTTvb
#define toolsBtnTextDisableColor OpLVmBVGqgPUybLX
#define toolsBtnTextSize aXKywShexZplryUu
#define cancelClickCallback OttRvlbHnmiFggZA
#define accordingArray ESWNUmCPRwHHlBKM
#define isInnerArray pLuUegKBDJhvclWE
#define currentUrlIndex FOlrZYICAnFGaylN
#define mainView kjPlnJhzeGpVorAc
#define leftView KDWEikworWlEaWPZ
#define rightView tzDyYkInanUAuTrM
#define topView AtSbdOejOewgBmlm
#define bottmView MNVdlifDLNfidmWe
#define gotoUrl XjeYurjqVkkDOPPN
#define resetBtnColor ogVaiHkeELZLkpRT
#define loadTitleUrl iIzkszwBdCIalQAV
#define setCancelCallback jyhdNMKsGADVaKFs
#define backBtnClick eMpcJeugYKDVQLDC
#define forwardBtnClick QSgQzvTaikYOUeXl
#define refreshBtnClick vkXjCRNfxPThDkSE
#define shareBtnClick uyTbDNZVVKMQSvCv
#define addMessageBtn PyAAxAZumCzYUfKC
#define messageBtn CgQJfZkcHJVYudoF
#define sendDiscussVC YRWFHUhoFpHpboTp
#define KeyboardControlExtension PWQNhOCuQZYdkURR
#define kvcIsKeyboardShow dpejtqvihdWzWeEL
#define kvcKeyboardHeight EtTFsRMzxbyJWRkx
#define kvcMainViewFrame yTqJZZSTyCjHrxTV
#define kvcTargetView OeAjwyznMTXmSFWn
#define KeyboardViewController dsprIdrESOKQPmtI
#define mainDisplacement XzrhtaSMFlVecJYY
#define bottomInputViewFrame ikxzZlQkcjkFiKVX
#define bottomSpace tFDDtNACqrydzWvg
#define bottomInputViewFrame NQgckcBaosadbfOQ
#define bottomSpace GhOyvbecwZcuHagf
#define kvcGetViewOfAbsoluteFame zNwtjeGNolyZkcCq
#define SendBirdNavigationController HuXZVCkSEcgiAyal
#define mTitleAttributes AmhpxEhcmqCftXan
#define UserInfoObject HzaMRwhVbircxjZB
#define userPassword QpbuMeLdtbSwmpBK
#define userNickname vFSHWvgScitxniUK
#define userEmail thweQMiLcQXCsHng
#define userImageUrl ehspAfwSmndgwMpV
#define AttentionObject zBCRfULmBFAqStOu
#define accordingUrlArray EFUuCavpQXELoXqd
#define NewPageObject WcpCCTQoIpEBhcIc
#define menuId nqcPDsEYVmutpSzk
#define cateName BYdtwVWhuyyETptl
#define titleName KVBGdrRYwhIIhreZ
#define subTitleName AmdznZdgRXrJhrWr
#define tagName MLIHSjAHAnUAYfOM
#define pageUrl bqaxBdhisXAecbSJ
#define imageUrl bUYXhYhyUpzdkALL
#define editTime lZtXHqxIclQlpGMN
#define isAttention nIsRlZGgLdAXzDhH
#define DiscussObject zjNJqiWbkDasCDgO
#define according DHndpEHNBntCjOqw
#define discussId ryTyznzWTcrAJgDh
#define subject eXUyiJMYcRjXUCcF
#define content XHDheCQnLemigZhO
#define date qCFcvAggzXaAVPjL
#define repostArray baRSLWYfElqtmwbY
#define like zUCTIhOpEKyNjPnK
#define DiscussAccordingObject WxAffAENYQacVwBq
#define accordingUrl tHxENcTbvduGjXTB
#define accordingImageUrl VGmdnCjQaYjyJbmg
#define accordingTitle ZdfLDpWESJbAGAVV
#define accordingSubTitle qZkxJRMMJDTuoyUS
#define DiscussRepostObject MThLpeJynymqmjxq
#define discussId xBIRLMbUmGZSTlTQ
#define DiscussLikeObject lKqIPuOyJqTetZXK
#define userInfoArray pzSDAHFntFjDwnnd
#define discussId LqmkqgXwmmuGsYVZ
#define sendBirdInit aDzcDJPxPrNeubnL
#define sendBirdAppId ouazXiALKioCqfYD
#define sendMessageTo GmBWvRecseyvdMzB
#define sendBirdChannelUrl mUPFQBpvcKcURpsm
#define userId uYvBeurjbDXXheEh
#define messageDic lzJbzUYZBdRtcKJO
#define didSendCallback bdsJrFVISxbMiWoY
#define getMessagesFrom hCnXlrtjGQSfThzC
#define sendBirdChannelUrl NkDOHpMajADRbvdm
#define numbersOfRange VpYbFyeZpzpcHaFq
#define messageArray PFsePuiEXmhmSqYC
#define pageOfNumbers iYYcTbpNQEcxjLSW
#define listQuery rezJZoeYjORFjLBU
#define getMessagesListQueryLoop vuZkPsPOGplTjzul
#define responseArray THDdTCzXUTNarjLi
#define userMsg pwmfajlKPRCbpdWi
#define msg mUQxWmSlonxPZlzg
#define msgData SuQZfyZpHqsJskNN
#define getSendBirdUserInfo SQBrONyoYjLekxcU
#define setSendBirdUserInfo hCHmeCGApjZiIiJP
#define sendAccountTo vwpMesapQgIFrTkZ
#define sendBirdAccountChannelUrl XranBTuFuScbJkvO
#define getAccountsFrom vmazeriZfXcEzCKE
#define sendDiscussTo pNggFatvgsrDpUQu
#define sendBirdDiscussChannelUrl ahfVYCotgVdjtIbp
#define discussObject HoKnUrDNuVnZWfyY
#define didSendCallback OIssRxiudDYZefiz
#define getDiscussesFrom QJScoTKnecFBnTjU
#define discussArray SWLYjCqRrYzcDlXQ
#define sendNewPageTo DDqRqKAlKpIbeKfh
#define sendBirdNewPageChannelUrl nStHRVdKItQoCVip
#define newPageObject idMeWMMmfRHhAVUk
#define getNewPagesFrom xkDFFPtiDmeiqsuq
#define newPageArray IfqXHkEludjdpZPL
#define prevMessageListQuery EsqQanDzTvlwYLue
#define sendUserAttentionTo JKGQcOlXtdmeRDJr
#define sendBirdAttentionChannelUrl GzjyMumOpQjiKlyc
#define attentionObject aKwpyTmrWXEwBpOO
#define getUserAttentionsFrom vzzIKPzZzZYHDdDV
#define attentionArray GzojPHMlAIHJoYNB
#define sendRepostTo CvLEegruBuVAaTjx
#define sendBirdRepostChannelUrl cqICjiHyeJUktcHL
#define repostObject ypgekSiqynlFxgcU
#define getRepostsFrom TmQvtIMwglgXgFcC
#define repostArray nRNeEKodXEmNzypn
#define sendLikeTo hXVdTuYXDRDLOpsg
#define sendBirdLikeChannelUrl XPsEPtkptpCGXtyz
#define likeObject kJBziCFAOUPBSbaI
#define getLikesFrom lWNUztRqgCIWMrzA
#define likeArray pPmdVrBMPULTNlbO
#define getOutermostView pBUOSHIeQygwkEol
#define getViewOfAbsoluteFame wTGkWdUYzAyxGdvi
#define startIndicator inYcQIOlOPNumrKx
#define currentVC mfcCvZkglwFJfXjK
#define onView LObTmqEXFNYyttNw
#define stopIndicator YOSpZKiQgQZNybEH
#define indicatorView rNmHRDKLsYaOTPju
#define matchPattern FXfYWcXsFIPFgAyT
#define regex wjYYDqLkUgYGxuXh
#define resizeImageLimited LPQpcLtCGDmUxgSz
#define backToViewController WFvSwQbhFFxwgdLO
#define backToVC FbgcAvWJtTPXrpKr
#define getDeviceTokenFromUserDefaults TwVkCSFQccPSoACx
#define saveDeviceTokenToUserDefaults whoKmOYKMEMUzFvp
#define deviceToken EixIPJcTmVXEOaWs
#define getCoreDataContext CdGjYIEdULgatnFJ
#define entityName jqNwXqHePzUogvyW
#define persistentContainer OGZHfolKVeFSTmtg
#define coreDataExample sUPcyLLSTRqtLHOr
#define uploadImageGetLink aWkYcrJWoAUzHKln
#define urlString BsroaqjaPsVyjMIU
#define authorization ESpquqoYLvVRUnKy
#define mashapeKey HhMiRmZYUFemWRrm
#define resizeImage GUiVgwXGjdCIYoIn
#define imageData wXJNpdZEjIFTcEJP
#define imageBase64 XjpcpvjqDmQBreoF
#define parameters tCHxUZbpdPIwBgIt
#define getDownArrow kTBCwPBlPlYNrFIa
#define isSameUrl yzfOuMwXZcvsKGUu
#define MatrixConcatenation NdwBHSBTyHRWRCXB
#define MatrixOrDouble HBZsxlnldkfBVshT
#define horizontalConcatenate ZYlDRxmLAwISgZPb
#define resData iQoSXychOwXGApzl
#define verticalConcatenate NyBgZQkKBtUeQAyW
#define Matrix PDwBbeaKPPngdyXk
#define AAPoint qNvCAhcrrUuZcLYR
#define translation IKuOBNpAkAEucFOb
#define MatrixMultiplication uUoozeaWpkYuuYNg
#define AASphereView fytTlQbxoDiPrvgR
#define MatrixCreation bwcNIxbXSGEncUcp
#define MatrixSubscripting naYUWlGxFTGUTLjA
#define sphereContentView SgPMtrxEqvkTujGn
#define sphereView mtMVOIvpUMJIrfmC
#define resetSphereView lHVyfTVCiiBiJUMe
#define showSphere bluBOkOVcYPepgmv
#define tags MlZooxFMZPRlgbIS
#define displaySize tBUFfLwytjMFrLSn
#define button KnHAmRHmeYEeUYdV
#define overWebVC MolxPMDDjVQeGTvc
#define accObj DNiseihxUWJqQnPM
#define CurrencyObject MpgpVZyBaGJknsJV
#define id NuWaMHJrsyznJqTq
#define currencyName GgxMpkyKJpknEPgk
#define currencySymbol WjoXaINrbYfoZHKZ
#define CurrencyTools wxvJusjhtCoyiwaV
#define freeCurrencyApiUrl yMLZEqNrmSJParTG
#define freeCurrencyAppKey tOoNOJSTUGIMzXmh
#define CurrencyName DTdVfeJXWAmIguad
#define en nbJNamoeydIIJtHJ
#define cn qXSKjonAVqDXifFS
#define getCurrencyNameCn ZzslhBsyMiUqItPK
#define getCurrencyObjectArray yFhpkiRSvwFISwLE
#define currencyArray AzIaixuAqaGuKlct
#define currencyDic YQsRPSCGRVvRtenI
#define currencyKey txFaJdBxsXzwTDLc
#define currencyName hxTMziacOTRIIobj
#define currencySymbol yGSKblZJvzKATKMb
#define currencyObj oPESxFJLkroYxkXP
#define currencyMainView MFmXqOihFRbqClSP
#define currencyTitleLabel TpoOsbcVkwQQdEaZ
#define currencyFromView uMtmDretTnapdnHs
#define currencyDescLabel1 LDmRQIhIzDrigReg
#define currencyToView EtLKMSAXeBoYBDTI
#define currencyDescLabel2 qstRFwHxbnUfacOI
#define currencyInputTextField fSpWBQVYaYkaJMMj
#define currencyStartBtn FtYUIFKkFkYeokgn
#define currencyResultTitleView dNTHEMVruTYZpAje
#define currencyResultTitleLabel xYhWxdJoXJrSRRdG
#define currencyResultLabelMain WMeiHeJAJHNgzbyN
#define currencyResultLabelSub KdOazBAvuwBXCJLY
#define currencyFromSpinner kbjtcurgkxnOWBDz
#define currencyToSpinner biMuBWLZxkTDWaRY
#define currencyObjectArray dOIgyfwxfBZLYvIE
#define currencyNameArray dmnXvfuoFXLgUhlP
#define currencyFromNameArray KMTUQFoiAxTgCTht
#define currencyToNameArray CjlIbkfAIRVvIqqV
#define isSpinnerInit LgwlrnNmOPRMKyEL
#define currencyObjArray dsdJsWaRTRdFHncX
#define valueText xQoKlzzgAATfpuRf
#define valueDouble pTTnFOqvvRuGjnov
#define fromObjIndex RuXPMllAWJbskPAM
#define toObjIndex ZbtRWqUWXwyTenOP
#define fromConName UqIfQTDletrWrtqJ
#define toConName jFtQXojjxifOuCHa
#define currencyPer QYxavrSkFVGgRfAo
#define per MsRefKrYDfdbuYhK
#define formatter xyCIppKSOZQqWhcw
#define valueString aYsDWuHQkYkNjTQI
#define abbs dNYbxIaTbulDzwzK
#define AbbsObject ifcQErIRXhOQYrTt
#define valx KUVpcrMBmczIDggj
#define valy ptJWFMGUMWecSaSE
#endif
